// Generated by kea-typegen on Thu, 26 Dec 2024 01:35:50 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface contactsLogicType extends Logic {
    actionCreators: {};
    actionKeys: {};
    actionTypes: {};
    actions: {};
    asyncActions: {};
    defaults: {};
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "scenes",
        "contacts",
        "contactsLogic"
    ];
    pathString: "scenes.contacts.contactsLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {};
    reducers: {};
    selector: (state: any) => {};
    selectors: {};
    sharedListeners: {};
    values: {};
    _isKea: true;
    _isKeaWithKey: false;
}