// Generated by kea-typegen on Tue, 31 Dec 2024 03:12:50 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ContactsProps } from './contactsLogic'

export interface contactsLogicType extends Logic {
    actionCreators: {};
    actionKeys: {};
    actionTypes: {};
    actions: {};
    asyncActions: {};
    defaults: {};
    events: {};
    key: string;
    listeners: {};
    path: [
        "scenes",
        "contacts",
        "contactsLogic",
        "*"
    ];
    pathString: "scenes.contacts.contactsLogic.*";
    props: ContactsProps;
    reducer: (state: any, action: any, fullState: any) => {};
    reducers: {};
    selector: (state: any) => {};
    selectors: {};
    sharedListeners: {};
    values: {};
    _isKea: true;
    _isKeaWithKey: true;
}