// Generated by kea-typegen on Wed, 15 Jan 2025 03:03:51 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { CrmFormSceneProps } from './CrmForm'

export interface crmFormLogicType extends Logic {
    actionCreators: {};
    actionKeys: {};
    actionTypes: {};
    actions: {};
    asyncActions: {};
    defaults: {};
    events: {};
    key: string;
    listeners: {};
    path: [
        "scenes",
        "forms",
        "crmFormLogic",
        "*"
    ];
    pathString: "scenes.forms.crmFormLogic.*";
    props: CrmFormSceneProps;
    reducer: (state: any, action: any, fullState: any) => {};
    reducers: {};
    selector: (state: any) => {};
    selectors: {
        formId: (state: any, props?: any) => string;
    };
    sharedListeners: {};
    values: {
        formId: string;
    };
    _isKea: true;
    _isKeaWithKey: true;
    __keaTypeGenInternalSelectorTypes: {
        formId: (arg: any) => string;
    };
}