// Generated by kea-typegen on Wed, 25 Dec 2024 01:18:23 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface breadcrumbLogicType extends Logic {
    actionCreators: {};
    actionKeys: {};
    actionTypes: {};
    actions: {};
    asyncActions: {};
    defaults: {};
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "src",
        "app",
        "components",
        "breadcrumb"
    ];
    pathString: "src.app.components.breadcrumb";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {};
    reducers: {};
    selector: (state: any) => {};
    selectors: {};
    sharedListeners: {};
    values: {};
    _isKea: true;
    _isKeaWithKey: false;
}