// Generated by kea-typegen on Mon, 23 Dec 2024 23:26:27 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface appLogicType extends Logic {
    actionCreators: {};
    actionKeys: {};
    actionTypes: {};
    actions: {};
    asyncActions: {};
    defaults: {};
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "src",
        "scenes",
        "app"
    ];
    pathString: "src.scenes.app";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {};
    reducers: {};
    selector: (state: any) => {};
    selectors: {
        isLoading: (state: any, props?: any) => boolean;
    };
    sharedListeners: {};
    values: {
        isLoading: boolean;
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        isLoading: (userLoading: boolean) => boolean;
    };
}